# Site settings
title:            Jason I. Carter
description:      Human Learning.
url:              #http://jasonicarter.github.io # Site url, without a slash at the end.
signoff:          Jason # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         LinkedIn
    url:          http://linkedin.com/in/jasoniancarter
    external:     true
  - name:         GitHub
    url:          http://github.com/jasonicarter
    external:     true
  - name:         Twitter
    url:          http://twitter.com/jasonicarter
    external:     true

# Build settings
permalink:  /:title/
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - _posts/*.Rmd
  - build.R

# Sass settings
sass:
    sass_dir: _sass # Jekyll default folder
    style: compressed
